spring:
  application:
    name: hotelServices
  config:
    import: optional:configserver:http://localhost:8084
  datasource:
    url: jdbc:mysql://localhost:3306/durgesh
    username: root
    password: 1962
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
