spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Srikant2021/microservice-configuration
          clone-on-start: true

  
server:
  port: 8084